### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#129]
[Colors based on Veera](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=936-92781&t=K9mg38u9TMmHWvxc-0)

**Comment by KaarelKa** [comment]
Moving this to blocked for now, since it seems that our design also uses the colors in the WCAG test section of the styleguide + some colors which are not mentioned in the styleguide.

This means that there are more than 240 colors to add. 

@martinepai Maybe we can narrow it down ? 

@MariusJulius If we can't narrow it down and all or a big part of those 240+ colors will be used, then it makes more sense to remove this task and developers will add the colors on the go
