### ISSUE TITLE
Export users (BE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#149]
[Wiki](https://github.com/keeleinstituut/tv-tolkevarav/wiki/5.-Autoriseerimine,--kasutajate-lisamine-s%C3%BCsteemi-(Kasutajate-ja-rollide-haldus)#6-exporting-users)

To-do:
- create an endpoint for fetching user list for download (or specify format for existing endpoint - difference in endpoint) (backend should return csv)
- validating user permissions for exporting - "Kasutajate nimekirja eksport" (export_user)

**Comment by DanBondarenko** [comment]
@MariusJulius I encountered the same vendor-related issue as in https://github.com/keeleinstituut/tv-tolkevarav/issues/137. Vendor status is stored in translation order service, not authorization service. 

However, with this issue, the solution is not as simple as in https://github.com/keeleinstituut/tv-tolkevarav/issues/137. Since this endpoint returns a CSV file, not JSON data, the front end can’t just trivially combine data from two endpoints. I see two approaches that make sense to me: 
1. Authorization service queries translation order service for vendor information.
2. We move this endpoint to translation order service. Translation order service queries authorization order service (or syncs data) to return CSV.

To me, the second approach seems better, since ideally we would like to avoid making authorization service dependent on translation order service. On the other hand, the other way around is fine.

@thenouan Tagging you so you have an opportunity to intervene as well.

**Comment by DanBondarenko** [comment]
For future reference, the following was decided ([link to Slack thread](https://pundar.slack.com/archives/C048W5ZV1ST/p1683807431372119)):
> Discussed with Birgit Plakso about the users and vendors. To keep the technical solution simpler and domain models more related to its direct bounded context we decided the following:
marking/unmarking of users as vendors will be removed from user management view. User management view's solely purpose will only be user management (it doesn't need to know about the vendors)
vendor database view will have new button at the top which navigates to a modal (or separate view) which will display all available users and has the possibility to mark the user as vendor or remove user from vendor list.
(available users are displayed based on the cached institution user information in translation-order-service to increase consistency)
> This simplifies the importing and exporting users logic in user management view
