### ISSUE TITLE
User authentication against keycloak in the Ordering portal web (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#68]
**To-do:**
- [x] #110
- [x] #109

Acceptance criteria:
- User can start login from the translation hub homepage
- After successful authentication user is directed to a temporary white screen confirming authentication (showing PIC)

**Comment by KaarelKa** [comment]
@MariusJulius What does PIC stand for ?

**Comment by MariusJulius** [comment]
Personal identification code (isikukood)

**Comment by KaarelKa** [comment]
@thenouan Do we have the keycloak configuration json already hosted somewhere, or the configuration options available somewhere ? 

@MariusJulius / @thenouan Could I also get access to Keycloak Admin Console, if it is set up ?

**Comment by KaarelKa** [comment]
@thenouan Okay currently tested it out locally and FE part is done. There is no keycloak side "log in", it just redirect back as "authenticated".

The PIC was just set as Client ID field in Keycloak Admin Console and is displayed in FE after authentication. 

Moving the tasked the task to "blocked" at the moment, since we don't have the actual keycloak.json for configuration

**Comment by KaarelKa** [comment]
@thenouan No need to check this anymore, got the answer from Dan
